# Generated by Django 5.1.1 on 2024-09-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='images/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
