# Generated by Django 5.1.1 on 2024-09-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='types',
            field=models.CharField(choices=[('trending', 'trending'), ('all books', 'all books')], default='-----', max_length=50),
        ),
    ]
