# Generated by Django 5.1.1 on 2024-10-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
        ),
    ]
